pre-commit.ci:
  autofix_commit_msg: |
    chore [pre-commit.ci] commit: auto fixes from pre-commit.ci hooks
  autoupdate_commit_msg: |
    chore [pre-commit.ci] pre-commit autoupdate
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_schedule: monthly
  push:
    branches:
      - main
  skip:
    - editorconfig-checker
    - trailing-whitespace
    - end-of-file-fixer
    - mixed-line-ending
    - check-yaml
  submodules: false
fail_fast: false
default_language_version:
  python: python3.12
repos:
  - repo: local
    hooks:
      - id: add-pre-commit-config
        name: Add pre-commit config
        entry: git add .pre-commit-config.yaml
        language: system
        pass_filenames: false
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
#  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
#    rev: 2.7.3
#    hooks:
#      - id: editorconfig-checker
#        alias: ec
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: ''  # Use the sha / tag you want to point at
#    hooks:
#      - id: prettier
#        types_or: [ html, css, javascript ]
#        additional_dependencies:
#          - prettier@2.1.2
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: '0.0.2' # Use the sha or tag you want to point at like 0.0.1
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@16.0.1
          - stylelint-config-standard@35.0.0
          - stylelint-config-tailwindcss@0.0.7
          - stylelint-config-recommended@14.0.0
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.55.0'  # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.55.0
          - eslint-standard@1.0.2
  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: 'v2.13.6'  # Use the sha / tag you want to point at
    hooks:
      - id: jshint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: \.md$
      - id: remove-tabs
        exclude: \.md$
        args: [ --whitespaces-count, '2' ]  # defaults to: 4
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.0.3
#    hooks:
#      - id: detect-secrets
#        args: ['--baseline', 'secrets.baseline']
#        exclude: 'secrets.baseline'
