---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on  :
  push        :
    branches-ignore: [main, site]
    #branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main, site]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name       : Lint Code Base
    # Set the agent to run on
    runs-on    : ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      -
        name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 1

      ################################
      # Run Linter against code base #
      ################################
      -
        name: Lint Code Base
        uses: super-linter/super-linter:slim-v5
        env :
          VALIDATE_ALL_CODEBASE : false
          DEFAULT_BRANCH : main
          CREATE_LOG_FILE : false
          CSS_FILE_NAME : .stylelintrc.json
          DEFAULT_WORKSPACE : ./../tmp/lint
          EDITORCONFIG_FILE_NAME : .editorconfig
          GITLEAKS_CONFIG_FILE : .gitleaks.toml
          JAVASCRIPT_DEFAULT_STYLE : standard
          JAVASCRIPT_ES_CONFIG_FILE : .eslintrc.js
          LINTER_RULES_PATH : /
          LOG_FILE_LOCATION : ./../tmp/logs/super-linter.log
          LOG_LEVEL : VERBOSE
          MULTI_STATUS : true
          SUPPRESS_FILE_TYPE_WARNINGS : false
          USE_FIND_ALGORITHM : true
          GITHUB_TOKEN : ${{ secrets.LINTER_TOKEN }}
